sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git /tmp/maintainer-quality-tools
  - export PATH=/tmp/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly 6.1
  - pip install coveralls flake8

script:
    - travis_run_flake8
    - travis_run_tests 6.1

after_success:
  coveralls
